import Header from "@/components/Header";
import Provider from "@/lib/context";
import "bootstrap/dist/css/bootstrap.min.css";
import { Open_Sans as OpenSans, Roboto_Slab as Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-roboto" });
const openSans = OpenSans({ subsets: ["latin"], variable: "--font-open-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${openSans.variable}`}>
        <Provider>
          <main className="min-h-screen flex flex-col">
            <Header />
            <div className="grow py-8">{children}</div>
            <Footer />
          </main>
        </Provider>
      </body>
    </html>
  );
}
